In [1]:
import math
import numpy as np
import scipy.stats as stats
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

from collections import defaultdict
from scipy.stats.stats import pearsonr
import pandas as pd

In [2]:
#load of the data
df_tennis = pd.read_csv('dataset/tennis_matches.csv', sep=',', index_col=0) 

#index_col=False say to not use the first column as ID
df_male = pd.read_csv('dataset/male_players.csv', sep=',', index_col=False)
df_female = pd.read_csv('dataset/female_players.csv', sep=',', index_col=False)

In [3]:
df_tennis.head()

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_entry,winner_name,...,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points,tourney_spectators,tourney_revenue
0,2019-M020,Brisbane,Hard,32.0,A,20181231.0,300.0,105453.0,NaN,Kei Nishikori,...,20.0,14.0,10.0,15.0,9.0,3590.0,16.0,1977.0,3928.0,742618.69
1,2019-M020,Brisbane,Hard,32.0,A,20181231.0,299.0,106421.0,NaN,Daniil Medvedev,...,7.0,10.0,10.0,13.0,16.0,1977.0,239.0,200.0,3928.0,742618.69
2,2019-M020,Brisbane,Hard,32.0,A,20181231.0,298.0,105453.0,NaN,Kei Nishikori,...,6.0,8.0,1.0,5.0,9.0,3590.0,40.0,1050.0,3928.0,742618.69
3,2019-M020,Brisbane,Hard,32.0,A,20181231.0,297.0,104542.0,PR,Jo-Wilfried Tsonga,...,9.0,11.0,4.0,6.0,239.0,200.0,31.0,1298.0,3928.0,742618.69
4,2019-M020,Brisbane,Hard,32.0,A,20181231.0,296.0,106421.0,NaN,Daniil Medvedev,...,19.0,15.0,2.0,4.0,16.0,1977.0,18.0,1855.0,3928.0,742618.69

# Male Table

Surname cleaning, in the surname are present substring with latters and numbers that clearly rappresents errors. The following code clears the surnames form this strings.

In [22]:
#ci sono cifre nei nomi/cognomi?
import re
re_name = "^^[a-zA-Z]+(([',. -][a-zA-Z ])?[a-zA-Z]*)*$"
wrong_surnames = []
wrong_surnames_indexes = []
for i,row in enumerate(df_male['surname']):
    if not(re.search(re_name, str(row))):
        wrong_surnames.append(str(row))
        wrong_surnames_indexes.append(i)

In [16]:
wrong_surnames

['Garcia G003',
 'Gonzalez G162',
 'Casey C100',
 'Phillips P239',
 'Jonsson J092',
 'Gutierrez G230',
 'Lindholm L174',
 'Turturici T225',
 'Brown B395',
 'Robinson R261',
 'Strengberger S597',
 'Parun P991',
 'Gonzalez G419',
 'Phillips Pd13',
 'Deleuran Skjold Db37',
 'Gomez Gb42',
 'Kocyla Kd20',
 'Weise W055',
 'Ukon U004',
 'Perez P114',
 'Pueski P199',
 'Pueski P223',
 'Robinson R263',
 'Wright W096',
 'Parun P071',
 'Khalfan K735',
 'Moore2',
 'Smith 2',
 'Day 3D',
 'Symington 3D',
 'Post 3Rd',
 'Leroy 2',
 'Bergevi Bl61',
 'Grant Gd13',
 'Hernandez Hb01',
 'Perez P727',
 'Lloyd L770',
 'Kovacs Kb22',
 'Fernandes F729',
 'Lindstrom2',
 'Ul Haq H325',
 'Ukon U033',
 'Ul Haq U022',
 'Goransson G423',
 'Antelo A325',
 'Roman R410',
 'Machkamov M741',
 'Williams W303',
 'Robert Rb04',
 'Fernandez F929',
 'Hassan Hb88',
 'Reyes Rc60',
 'Colorado ',
 'Bye1',
 'Cabrera (Chi)',
 'Borras ',
 'Huttrup ',
 'Mullen ',
 'Kepler ',
 'Martin (Bra)',
 '1',
 'Quintero Aguilar ',
 'Hatzis ',
 'Ktiri ',
 'Arabaci ',
 'Dous Karpenschif ',
 'Paris ',
 'Compagnucci ',
 'Privara ',
 'Poljicak ',
 'Kovkin ',
 'Odani ',
 'Westphal ',
 'Faucon ',
 'Alimli ',
 'Oueslati ',
 'Eldiyar Uulu ',
 'Paliska ',
 'Villoslada ',
 'Karol ',
 'Raynel ',
 'Sodan ',
 'Merida Aguilar ',
 'Sharma ',
 'Benchakroun ',
 'Stakusic ',
 'Mihailovic ',
 'Cervinka ',
 'Ferri ']

In [62]:
correct_surname = []
for wrong_surname in wrong_surnames_indexes:
    words = str(df_male['surname'][wrong_surname]).split(" ")
    #se Ã¨ =1 togliamo solo il numero dalla parola.
    if len(words)==1:
        for caracter in words[0]:
            if caracter.isdigit():
                words[0] = words[0].replace(str(caracter),"")
        correct_surname.append(words[0])
    #se >1 togliamo la seconda parola se ci sono numeri
    if len(words)>1:
        for word in words:
            if not(re.search(re_name, str(word))):
                words.remove(word)
            #check se tutte le parole hanno len>1: se no toglile
#            if len(word)==1:
 #               words.remove(word)
        correct_surname.append(' '.join(words))

In [63]:
correct_surname

['Garcia',
 'Gonzalez',
 'Casey',
 'Phillips',
 'Jonsson',
 'Gutierrez',
 'Lindholm',
 'Turturici',
 'Brown',
 'Robinson',
 'Strengberger',
 'Parun',
 'Gonzalez',
 'Phillips',
 'DeleuranSkjold',
 'Gomez',
 'Kocyla',
 'Weise',
 'Ukon',
 'Perez',
 'Pueski',
 'Pueski',
 'Robinson',
 'Wright',
 'Parun',
 'Khalfan',
 'Moore',
 'Smith',
 'Day',
 'Symington',
 'Post',
 'Leroy',
 'Bergevi',
 'Grant',
 'Hernandez',
 'Perez',
 'Lloyd',
 'Kovacs',
 'Fernandes',
 'Lindstrom',
 'UlHaq',
 'Ukon',
 'UlHaq',
 'Goransson',
 'Antelo',
 'Roman',
 'Machkamov',
 'Williams',
 'Robert',
 'Fernandez',
 'Hassan',
 'Reyes',
 'Colorado',
 'Bye',
 'Cabrera',
 'Borras',
 'Huttrup',
 'Mullen',
 'Kepler',
 'Martin',
 '',
 'QuinteroAguilar',
 'Hatzis',
 'Ktiri',
 'Arabaci',
 'DousKarpenschif',
 'Paris',
 'Compagnucci',
 'Privara',
 'Poljicak',
 'Kovkin',
 'Odani',
 'Westphal',
 'Faucon',
 'Alimli',
 'Oueslati',
 'EldiyarUulu',
 'Paliska',
 'Villoslada',
 'Karol',
 'Raynel',
 'Sodan',
 'MeridaAguilar',
 'Sharma',
 'Benchakroun',
 'Stakusic',
 'Mihailovic',
 'Cervinka',
 'Ferri']